// Generated by tools/audio/pipeline.ts. Do not edit by hand.

export type SoundId =
  | "shot.rifle.near"
  | "shot.rifle.far"
  | "shot.shotgun.near"
  | "shot.shotgun.far"
  | "shot.pistol.near"
  | "shot.pistol.far"
  | "shot.sniper.near"
  | "shot.sniper.far"
  | "shot.sniper.tail"
  | "mech.rifle.magOut"
  | "mech.rifle.magIn"
  | "mech.pistol.magOut"
  | "mech.pistol.magIn"
  | "mech.pistol.slide"
  | "mech.bolt.open"
  | "mech.bolt.close"
  | "mech.charge"
  | "mech.shotgun.pump"
  | "mech.shotgun.shell"
  | "mech.dryFire"
  | "mech.latch"
  | "foley.cloth"
  | "foley.casing"
  | "foley.land"
  | "step.concrete"
  | "step.dirt"
  | "step.grass"
  | "step.wood"
  | "step.metal"
  | "step.gravel"
  | "impact.concrete"
  | "impact.metal"
  | "impact.wood"
  | "impact.dirt"
  | "impact.flesh"
  | "amb.wind"
  | "amb.birds"
  | "amb.birdCall";

export interface SoundVariant {
  /** File name without extension, relative to AUDIO_ROOT. */
  readonly file: string;
  /** Seconds. */
  readonly duration: number;
}

export interface SoundAsset {
  /** 1 = mono (spatialized in the world), 2 = stereo (first person, ambience). */
  readonly channels: 1 | 2;
  /** eager: decoded at startup; lazy: decoded on first use or in the background. */
  readonly load: "eager" | "lazy";
  readonly variants: readonly SoundVariant[];
}

/** Encodings in order of preference; the first one the browser can decode wins. */
export const AUDIO_FORMATS = [
  { ext: "ogg", mime: 'audio/ogg; codecs="opus"' },
  { ext: "m4a", mime: 'audio/mp4; codecs="mp4a.40.2"' },
] as const;

export const AUDIO_ROOT = "assets/audio/";

export const AUDIO_MANIFEST: Readonly<Record<SoundId, SoundAsset>> = {
  "shot.rifle.near": { channels: 2, load: "eager", variants: [{ file: "shot.rifle.near.0", duration: 1.1000 }, { file: "shot.rifle.near.1", duration: 1.1000 }, { file: "shot.rifle.near.2", duration: 1.1000 }, { file: "shot.rifle.near.3", duration: 1.1000 }, { file: "shot.rifle.near.4", duration: 1.1000 }] },
  "shot.rifle.far": { channels: 1, load: "eager", variants: [{ file: "shot.rifle.far.0", duration: 2.6000 }, { file: "shot.rifle.far.1", duration: 2.5790 }, { file: "shot.rifle.far.2", duration: 2.6000 }, { file: "shot.rifle.far.3", duration: 2.6000 }] },
  "shot.shotgun.near": { channels: 2, load: "eager", variants: [{ file: "shot.shotgun.near.0", duration: 1.3000 }, { file: "shot.shotgun.near.1", duration: 1.3000 }, { file: "shot.shotgun.near.2", duration: 1.3000 }, { file: "shot.shotgun.near.3", duration: 1.3000 }, { file: "shot.shotgun.near.4", duration: 1.3000 }, { file: "shot.shotgun.near.5", duration: 1.3000 }] },
  "shot.shotgun.far": { channels: 1, load: "eager", variants: [{ file: "shot.shotgun.far.0", duration: 2.6000 }, { file: "shot.shotgun.far.1", duration: 2.6000 }, { file: "shot.shotgun.far.2", duration: 2.6000 }, { file: "shot.shotgun.far.3", duration: 2.6000 }, { file: "shot.shotgun.far.4", duration: 2.6000 }, { file: "shot.shotgun.far.5", duration: 2.6000 }] },
  "shot.pistol.near": { channels: 2, load: "eager", variants: [{ file: "shot.pistol.near.0", duration: 0.9000 }, { file: "shot.pistol.near.1", duration: 0.9000 }, { file: "shot.pistol.near.2", duration: 0.9000 }, { file: "shot.pistol.near.3", duration: 0.9000 }, { file: "shot.pistol.near.4", duration: 0.9000 }] },
  "shot.pistol.far": { channels: 1, load: "eager", variants: [{ file: "shot.pistol.far.0", duration: 2.2000 }, { file: "shot.pistol.far.1", duration: 2.2000 }, { file: "shot.pistol.far.2", duration: 2.2000 }, { file: "shot.pistol.far.3", duration: 2.2000 }] },
  "shot.sniper.near": { channels: 2, load: "eager", variants: [{ file: "shot.sniper.near.0", duration: 1.8000 }, { file: "shot.sniper.near.1", duration: 1.8000 }, { file: "shot.sniper.near.2", duration: 1.8000 }, { file: "shot.sniper.near.3", duration: 1.8000 }, { file: "shot.sniper.near.4", duration: 1.8000 }, { file: "shot.sniper.near.5", duration: 1.8000 }] },
  "shot.sniper.far": { channels: 1, load: "eager", variants: [{ file: "shot.sniper.far.0", duration: 3.2000 }, { file: "shot.sniper.far.1", duration: 3.2000 }, { file: "shot.sniper.far.2", duration: 3.2000 }, { file: "shot.sniper.far.3", duration: 3.2000 }, { file: "shot.sniper.far.4", duration: 3.2000 }, { file: "shot.sniper.far.5", duration: 3.2000 }] },
  "shot.sniper.tail": { channels: 2, load: "eager", variants: [{ file: "shot.sniper.tail.0", duration: 2.5000 }, { file: "shot.sniper.tail.1", duration: 2.5000 }, { file: "shot.sniper.tail.2", duration: 2.5000 }, { file: "shot.sniper.tail.3", duration: 2.5000 }, { file: "shot.sniper.tail.4", duration: 2.5000 }, { file: "shot.sniper.tail.5", duration: 2.5000 }] },
  "mech.rifle.magOut": { channels: 1, load: "eager", variants: [{ file: "mech.rifle.magOut.0", duration: 0.4565 }] },
  "mech.rifle.magIn": { channels: 1, load: "eager", variants: [{ file: "mech.rifle.magIn.0", duration: 0.5065 }] },
  "mech.pistol.magOut": { channels: 1, load: "eager", variants: [{ file: "mech.pistol.magOut.0", duration: 0.3565 }] },
  "mech.pistol.magIn": { channels: 1, load: "eager", variants: [{ file: "mech.pistol.magIn.0", duration: 0.4065 }] },
  "mech.pistol.slide": { channels: 1, load: "eager", variants: [{ file: "mech.pistol.slide.0", duration: 0.4565 }] },
  "mech.bolt.open": { channels: 1, load: "eager", variants: [{ file: "mech.bolt.open.0", duration: 0.3565 }, { file: "mech.bolt.open.1", duration: 0.3565 }, { file: "mech.bolt.open.2", duration: 0.3565 }, { file: "mech.bolt.open.3", duration: 0.3565 }] },
  "mech.bolt.close": { channels: 1, load: "eager", variants: [{ file: "mech.bolt.close.0", duration: 0.3565 }, { file: "mech.bolt.close.1", duration: 0.3565 }, { file: "mech.bolt.close.2", duration: 0.3565 }, { file: "mech.bolt.close.3", duration: 0.3565 }] },
  "mech.charge": { channels: 1, load: "eager", variants: [{ file: "mech.charge.0", duration: 0.3065 }, { file: "mech.charge.1", duration: 0.3065 }, { file: "mech.charge.2", duration: 0.3065 }, { file: "mech.charge.3", duration: 0.3065 }] },
  "mech.shotgun.pump": { channels: 1, load: "eager", variants: [{ file: "mech.shotgun.pump.0", duration: 0.5008 }] },
  "mech.shotgun.shell": { channels: 1, load: "eager", variants: [{ file: "mech.shotgun.shell.0", duration: 0.6565 }, { file: "mech.shotgun.shell.1", duration: 0.6565 }, { file: "mech.shotgun.shell.2", duration: 0.6565 }, { file: "mech.shotgun.shell.3", duration: 0.6565 }] },
  "mech.dryFire": { channels: 1, load: "eager", variants: [{ file: "mech.dryFire.0", duration: 0.2065 }, { file: "mech.dryFire.1", duration: 0.2065 }] },
  "mech.latch": { channels: 1, load: "eager", variants: [{ file: "mech.latch.0", duration: 0.3065 }, { file: "mech.latch.1", duration: 0.3065 }, { file: "mech.latch.2", duration: 0.3065 }] },
  "foley.cloth": { channels: 1, load: "eager", variants: [{ file: "foley.cloth.0", duration: 0.1082 }, { file: "foley.cloth.1", duration: 0.0823 }, { file: "foley.cloth.2", duration: 0.1209 }, { file: "foley.cloth.3", duration: 0.1205 }] },
  "foley.casing": { channels: 1, load: "eager", variants: [{ file: "foley.casing.0", duration: 0.3536 }, { file: "foley.casing.1", duration: 0.2554 }, { file: "foley.casing.2", duration: 0.2394 }, { file: "foley.casing.3", duration: 0.3565 }, { file: "foley.casing.4", duration: 0.2170 }] },
  "foley.land": { channels: 1, load: "eager", variants: [{ file: "foley.land.0", duration: 0.5036 }, { file: "foley.land.1", duration: 0.5036 }, { file: "foley.land.2", duration: 0.5036 }, { file: "foley.land.3", duration: 0.5036 }, { file: "foley.land.4", duration: 0.5036 }] },
  "step.concrete": { channels: 1, load: "eager", variants: [{ file: "step.concrete.0", duration: 0.3794 }, { file: "step.concrete.1", duration: 0.3333 }, { file: "step.concrete.2", duration: 0.3369 }, { file: "step.concrete.3", duration: 0.3624 }, { file: "step.concrete.4", duration: 0.3168 }, { file: "step.concrete.5", duration: 0.3430 }] },
  "step.dirt": { channels: 1, load: "eager", variants: [{ file: "step.dirt.0", duration: 0.4065 }, { file: "step.dirt.1", duration: 0.3184 }, { file: "step.dirt.2", duration: 0.2979 }, { file: "step.dirt.3", duration: 0.4006 }, { file: "step.dirt.4", duration: 0.3177 }, { file: "step.dirt.5", duration: 0.3246 }] },
  "step.grass": { channels: 1, load: "eager", variants: [{ file: "step.grass.0", duration: 0.4036 }, { file: "step.grass.1", duration: 0.4036 }, { file: "step.grass.2", duration: 0.4036 }, { file: "step.grass.3", duration: 0.4036 }, { file: "step.grass.4", duration: 0.4036 }] },
  "step.wood": { channels: 1, load: "eager", variants: [{ file: "step.wood.0", duration: 0.2532 }, { file: "step.wood.1", duration: 0.2552 }, { file: "step.wood.2", duration: 0.2550 }, { file: "step.wood.3", duration: 0.2551 }, { file: "step.wood.4", duration: 0.2515 }] },
  "step.metal": { channels: 1, load: "eager", variants: [{ file: "step.metal.0", duration: 0.4065 }, { file: "step.metal.1", duration: 0.4065 }, { file: "step.metal.2", duration: 0.4065 }, { file: "step.metal.3", duration: 0.4065 }, { file: "step.metal.4", duration: 0.4065 }] },
  "step.gravel": { channels: 1, load: "eager", variants: [{ file: "step.gravel.0", duration: 0.4488 }, { file: "step.gravel.1", duration: 0.5065 }, { file: "step.gravel.2", duration: 0.5065 }, { file: "step.gravel.3", duration: 0.5065 }, { file: "step.gravel.4", duration: 0.5065 }, { file: "step.gravel.5", duration: 0.5065 }] },
  "impact.concrete": { channels: 1, load: "eager", variants: [{ file: "impact.concrete.0", duration: 0.4565 }, { file: "impact.concrete.1", duration: 0.4565 }, { file: "impact.concrete.2", duration: 0.4565 }, { file: "impact.concrete.3", duration: 0.4565 }, { file: "impact.concrete.4", duration: 0.4565 }] },
  "impact.metal": { channels: 1, load: "eager", variants: [{ file: "impact.metal.0", duration: 0.2754 }, { file: "impact.metal.1", duration: 0.1470 }, { file: "impact.metal.2", duration: 0.1227 }, { file: "impact.metal.3", duration: 0.2576 }, { file: "impact.metal.4", duration: 0.1130 }] },
  "impact.wood": { channels: 1, load: "eager", variants: [{ file: "impact.wood.0", duration: 0.4565 }, { file: "impact.wood.1", duration: 0.4565 }, { file: "impact.wood.2", duration: 0.4565 }, { file: "impact.wood.3", duration: 0.4565 }, { file: "impact.wood.4", duration: 0.4565 }] },
  "impact.dirt": { channels: 1, load: "eager", variants: [{ file: "impact.dirt.0", duration: 0.1216 }, { file: "impact.dirt.1", duration: 0.1869 }, { file: "impact.dirt.2", duration: 0.1388 }, { file: "impact.dirt.3", duration: 0.1438 }, { file: "impact.dirt.4", duration: 0.1507 }] },
  "impact.flesh": { channels: 1, load: "eager", variants: [{ file: "impact.flesh.0", duration: 0.3565 }, { file: "impact.flesh.1", duration: 0.3565 }, { file: "impact.flesh.2", duration: 0.3565 }, { file: "impact.flesh.3", duration: 0.3565 }, { file: "impact.flesh.4", duration: 0.3565 }] },
  "amb.wind": { channels: 2, load: "lazy", variants: [{ file: "amb.wind.0", duration: 45.0065 }] },
  "amb.birds": { channels: 2, load: "lazy", variants: [{ file: "amb.birds.0", duration: 45.0065 }] },
  "amb.birdCall": { channels: 1, load: "lazy", variants: [{ file: "amb.birdCall.0", duration: 3.0065 }, { file: "amb.birdCall.1", duration: 2.0717 }, { file: "amb.birdCall.2", duration: 3.0065 }, { file: "amb.birdCall.3", duration: 3.0065 }, { file: "amb.birdCall.4", duration: 3.0065 }, { file: "amb.birdCall.5", duration: 3.0065 }, { file: "amb.birdCall.6", duration: 3.0158 }] },
};
