#!/usr/bin/env node
// Builds the Vietnamese street set (vn/config.mjs) with the prop pipeline (../props.mjs buildModel):
//   public/assets/environment/vn/<model>.glb   `<propId>_LOD<n>` root nodes, KTX2 textures, meshopt geometry
//   public/assets/environment/vn/build.json    measured records
//   apps/client/src/assets/vnPropsManifest.ts  generated manifest (not wired into maps; see docs/assets-vietnam.md)
// Debug side views land in assets-src/environment/.cache/previews/<propId>.png.
// Usage: node tools/environment/vn/build.mjs [--only=model,model]   (one model at a time, one texture worker)
import { readFile, mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { createIO } from "../../assets/lib/gltf.ts";
import { TextureEncoderPool } from "../../assets/lib/textures.ts";
import { CACHE_DIR, OUT_DIR, REPO_ROOT } from "../config.mjs";
import { simplifierReady } from "../geometry.mjs";
import { buildModel, upsertCredits } from "../props.mjs";
import { VN_MODELS, VN_MODELS_DIR, VN_PROPS, VN_URL_DIR } from "./config.mjs";

setTimeout(() => {
  console.error("aborted after 2400 s");
  process.exit(2);
}, 2_400_000).unref();

const RECORD_FILE = path.join(OUT_DIR, VN_URL_DIR, "build.json");
const MANIFEST_TS = path.join(REPO_ROOT, "apps/client/src/assets/vnPropsManifest.ts");
const HINT_KEYS = ["category", "group", "surface", "castShadow", "cullDistance", "scaleRange", "use"];

async function main() {
  const only = process.argv.find((a) => a.startsWith("--only="))?.slice(7).split(",");
  await simplifierReady();
  await mkdir(path.join(OUT_DIR, VN_URL_DIR), { recursive: true });
  const io = await createIO();
  const pool = new TextureEncoderPool(CACHE_DIR, 1);
  const creditsFile = path.join(OUT_DIR, "credits.json");
  const creditsBody = JSON.parse(await readFile(creditsFile, "utf8"));
  const record = await readFile(RECORD_FILE, "utf8").then(JSON.parse, () => ({ props: {} }));
  try {
    for (const model of VN_MODELS) {
      const props = VN_PROPS.filter((p) => p.model === model.id);
      if (model.skip || props.length === 0 || (only && !only.includes(model.id))) continue;
      const started = performance.now();
      const resolved = await Promise.all(props.map((prop) => resolveNodes(model, prop)));
      const credit = creditsBody.assets.find((c) => c.id === model.id);
      const entries = await buildModel(io, pool, { ...model, preview: true }, resolved, credit, { modelsDir: VN_MODELS_DIR, urlDir: VN_URL_DIR });
      for (const prop of props) {
        const entry = entries[prop.id];
        if (prop.collisionOverride) entry.collision = overrideCollision(prop.collisionOverride, entry.bounds);
        record.props[prop.id] = { ...entry, ...Object.fromEntries(HINT_KEYS.map((k) => [k, prop[k]])) };
      }
      await writeFile(RECORD_FILE, `${JSON.stringify(record, null, 1)}\n`);
      if (model.credits && upsertCredits(creditsBody.assets, model.credits.map((c) => ({ ...c, set: "vn" })))) {
        await writeFile(creditsFile, `${JSON.stringify(creditsBody, null, 2)}\n`);
      }
      console.log(`${model.id}: ${((performance.now() - started) / 1000).toFixed(1)} s, rss ${(process.memoryUsage().rss / 1e6).toFixed(0)} MB`);
    }
  } finally {
    await pool.close();
  }
  // Drop records of props no longer configured.
  for (const id of Object.keys(record.props)) if (!VN_PROPS.some((p) => p.id === id)) delete record.props[id];
  await writeFile(RECORD_FILE, `${JSON.stringify(record, null, 1)}\n`);
  await writeManifest(record);
  let total = 0;
  for (const file of await readdir(path.join(OUT_DIR, VN_URL_DIR))) total += (await stat(path.join(OUT_DIR, VN_URL_DIR, file))).size;
  console.log(`vn/: ${(total / 1e6).toFixed(2)} MB, ${Object.keys(record.props).length} props`);
}

/** Expands `nodePrefix` into the node names of the source glTF. */
async function resolveNodes(model, prop) {
  if (!prop.nodePrefix) return prop;
  const json = JSON.parse(await readFile(path.join(VN_MODELS_DIR, model.id, `${model.id}.gltf`), "utf8"));
  const nodes = json.nodes.filter((n) => n.mesh !== undefined && n.name.startsWith(prop.nodePrefix)).map((n) => n.name);
  if (nodes.length === 0) throw new Error(`${prop.id}: no nodes start with ${prop.nodePrefix}`);
  return { ...prop, nodes };
}

function overrideCollision({ kind, radius, height }, bounds) {
  if (kind !== "cylinder") throw new Error(`collisionOverride ${kind} is not supported`);
  const h = Number((height ?? bounds.max[1]).toFixed(3));
  return { kind: "cylinder", center: [0, h / 2, 0], radius, height: h };
}

async function writeManifest({ props }) {
  const ids = VN_PROPS.map((p) => p.id).filter((id) => props[id]);
  const body = `// Generated by tools/environment/vn/build.mjs. Do not edit by hand; re-run the script instead.
// Vietnamese street set: paths are relative to the environment asset root (public/assets/environment/). Most are not
// placed yet; the wilderness plants are placed from layout/props.ts. docs/assets-vietnam.md has the catalog and credits.

import type { GeneratedPropAsset, PropCategory, PropSurface } from "../world/propAssets";

export type VnPropGroup = "sidewalk" | "shopfront" | "wall" | "rooftop" | "utility" | "market" | "construction" | "plants" | "trees" | "vehicles";

export interface VnPropAsset extends GeneratedPropAsset {
  readonly category: PropCategory;
  readonly group: VnPropGroup;
  readonly surface: PropSurface;
  readonly castShadow: boolean;
  readonly cullDistance: number;
  readonly scaleRange: readonly [min: number, max: number];
  /** Where it belongs on a Saigon street. */
  readonly use: string;
}

export const VN_PROP_IDS = [
${ids.map((id) => `  "${id}",`).join("\n")}
] as const;

export type VnPropId = (typeof VN_PROP_IDS)[number];

export const VN_PROP_MANIFEST: Readonly<Record<VnPropId, VnPropAsset>> = {
${ids.map((id) => `  ${id}: ${JSON.stringify(props[id])},`).join("\n")}
};
`;
  await writeFile(MANIFEST_TS, body);
  console.log(`wrote ${path.relative(REPO_ROOT, MANIFEST_TS)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
