// Generated by tools/map/build.ts --map mazebr; do not edit. Rebuild after changing the maze terrain, flatten regions or walls.
export const MAZE_BR_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "f261bf9a",
  terrainChecksum: "ef85b631-94dc5344",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "0e281a7f",
  bytes: 148133,
} as const;
