// Generated by tools/map/build.ts --map mazebr; do not edit. Rebuild after changing the maze terrain, flatten regions or walls.
export const MAZE_BR_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "8fcd0b17",
  terrainChecksum: "d5986bf5-2a5f99a0",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "34a8b80e",
  bytes: 363508,
} as const;
