// Generated by tools/environment/process.mjs. Do not edit by hand; re-run the script instead.
// Paths are relative to the environment asset root (public/assets/environment/).

export type Vec3 = readonly [number, number, number];

export interface TextureSetFiles {
  /** Real-world size of one texture tile, in meters. */
  readonly meters: number;
  readonly albedo: string;
  readonly normal?: string;
  /** Packed AO (R), roughness (G), metalness (B). */
  readonly arm?: string;
  /** Mean albedo in linear space. */
  readonly meanAlbedo: Vec3;
}

export const TEXTURE_SETS = {
  aerial_grass_rock: { meters: 15, albedo: "textures/aerial_grass_rock_diff_512.jpg", meanAlbedo: [0.1698, 0.1227, 0.0274] },
  asphalt_02: { meters: 3, albedo: "textures/asphalt_02_diff_1k.jpg", normal: "textures/asphalt_02_nor_gl_1k.jpg", arm: "textures/asphalt_02_arm_1k.jpg", meanAlbedo: [0.1122, 0.1099, 0.0977] },
  concrete_floor_worn_001: { meters: 3, albedo: "textures/concrete_floor_worn_001_diff_2k.jpg", normal: "textures/concrete_floor_worn_001_nor_gl_1k.jpg", arm: "textures/concrete_floor_worn_001_arm_1k.jpg", meanAlbedo: [0.0921, 0.0950, 0.0888] },
  concrete_wall_008: { meters: 2.71, albedo: "textures/concrete_wall_008_diff_2k.jpg", normal: "textures/concrete_wall_008_nor_gl_2k.jpg", arm: "textures/concrete_wall_008_arm_1k.jpg", meanAlbedo: [0.2655, 0.2381, 0.1607] },
  corrugated_iron_02: { meters: 2.7, albedo: "textures/corrugated_iron_02_diff_1k.jpg", normal: "textures/corrugated_iron_02_nor_gl_1k.jpg", arm: "textures/corrugated_iron_02_arm_1k.jpg", meanAlbedo: [0.0993, 0.0985, 0.0826] },
  forrest_ground_01: { meters: 2, albedo: "textures/forrest_ground_01_diff_2k.jpg", normal: "textures/forrest_ground_01_nor_gl_1k.jpg", arm: "textures/forrest_ground_01_arm_1k.jpg", meanAlbedo: [0.2939, 0.2515, 0.1223] },
  rusty_metal_02: { meters: 1, albedo: "textures/rusty_metal_02_diff_1k.jpg", normal: "textures/rusty_metal_02_nor_gl_1k.jpg", arm: "textures/rusty_metal_02_arm_1k.jpg", meanAlbedo: [0.4137, 0.2892, 0.1375] },
  weathered_planks: { meters: 2, albedo: "textures/weathered_planks_diff_1k.jpg", normal: "textures/weathered_planks_nor_gl_1k.jpg", arm: "textures/weathered_planks_arm_1k.jpg", meanAlbedo: [0.0818, 0.0590, 0.0438] },
} as const satisfies Record<string, TextureSetFiles>;

export type TextureSetId = keyof typeof TEXTURE_SETS;

export const SKY = {
  /** Sun-less, ground-filled equirectangular panorama for IBL (prefiltered at load). */
  iblPanorama: "sky/kloofendal_48d_partly_cloudy_puresky_ibl_1k.hdr",
  /** Skybox faces in Babylon CubeTexture order: +X, +Y, +Z, -X, -Y, -Z. */
  faces: ["sky/sky_px.jpg", "sky/sky_py.jpg", "sky/sky_pz.jpg", "sky/sky_nx.jpg", "sky/sky_ny.jpg", "sky/sky_nz.jpg"],
  /** Multiply the sRGB-decoded sky faces by this to get back to panorama units. */
  skyScale: 2.903,
  /** Unit vector pointing from the scene toward the sun. */
  sunDirection: [-0.5495, 0.7416, -0.3848] as Vec3,
  sunColor: [0.991, 1, 0.9113] as Vec3,
  /** DirectionalLight intensity matching the energy removed from the panorama (E_sun / π). */
  sunIntensity: 1.4953,
  sunElevationDeg: 47.8666,
  /** Sky-only horizontal irradiance / π (what a hemispheric fill light should approximate). */
  skyAmbient: 0.5004,
  /** Mean linear radiance of the sky just above the horizon (fog/haze color). */
  horizonColor: [0.4601, 0.4941, 0.5986] as Vec3,
  /** Radiance of the sun- and sky-lit ground that fills the panorama below the horizon. */
  groundRadiance: [0.45, 0.4042, 0.2119] as Vec3,
} as const;
