// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "1dc5ef23",
  terrainChecksum: "5e374718-c9aae53e",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "88a2a717",
  bytes: 2422736,
} as const;
