// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "8fdca275",
  terrainChecksum: "a9ad0c55-c76e2782",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "ce63f1c3",
  bytes: 2418711,
} as const;
