// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "adc0ac50",
  terrainChecksum: "fcf8b81b-9e69d8e4",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "5dde2006",
  bytes: 607870,
} as const;
