// Build record (public/assets/environment/build.json) and the generated TS manifest shared by process.mjs and props.mjs.
import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { MANIFEST_TS, OUT_DIR } from "./config.mjs";

const RECORD_FILE = path.join(OUT_DIR, "build.json");

/** { textures, sky, props }: whatever the last runs of each step produced. */
export async function readBuildRecord() {
  try {
    return JSON.parse(await readFile(RECORD_FILE, "utf8"));
  } catch {
    return { textures: {}, sky: null, props: {} };
  }
}

export async function writeBuildRecord(record) {
  await writeFile(RECORD_FILE, `${JSON.stringify(record, null, 1)}\n`);
}

export async function writeManifest({ textures, sky, props }) {
  if (!sky || !textures.forrest_ground_01) throw new Error("build.json lacks sky or texture records; run process.mjs first");
  const round = (v) => Number(v.toFixed(4));
  const texturesTs = Object.entries(textures)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, set]) => {
      const files = Object.entries(set.files)
        .map(([map, file]) => `${map === "nor_gl" ? "normal" : map === "diff" ? "albedo" : map}: "${file}"`)
        .join(", ");
      const mean = set.meanAlbedo.map((v) => v.toFixed(4)).join(", ");
      const roughness = set.roughness === undefined ? "" : `, roughness: ${round(set.roughness)}`;
      return `  ${id}: { meters: ${set.meters}, ${files}, meanAlbedo: [${mean}]${roughness} },`;
    })
    .join("\n");
  const propsTs = Object.entries(props ?? {})
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, asset]) => `  ${id}: ${JSON.stringify(asset)},`)
    .join("\n");
  const tuple = (v) => `[${v.join(", ")}]`;
  const body = `// Generated by tools/environment (process.mjs, props.mjs). Do not edit by hand; re-run the scripts instead.
// Paths are relative to the environment asset root (public/assets/environment/).

import type { GeneratedPropAsset, PropId } from "./propAssets";

export type Vec3 = readonly [number, number, number];

export interface TextureSetFiles {
  /** Real-world size of one texture tile, in meters. */
  readonly meters: number;
  readonly albedo: string;
  readonly normal?: string;
  /** Packed AO (R), roughness (G), metalness (B). */
  readonly arm?: string;
  /** Packed normal X (R), normal Y (G), AO (B) for terrain layers; reconstruct Z. */
  readonly nxa?: string;
  /** Mean albedo in linear space. */
  readonly meanAlbedo: Vec3;
  /** Mean roughness (from the ARM source), for sets shipped as NXA. */
  readonly roughness?: number;
}

export const TEXTURE_SETS = {
${texturesTs}
} as const satisfies Record<string, TextureSetFiles>;

export type TextureSetId = keyof typeof TEXTURE_SETS;

export const SKY = {
  /** Sun-less, ground-filled equirectangular panorama for IBL (prefiltered at load). */
  iblPanorama: "${sky.iblPanorama}",
  /** Skybox faces in Babylon CubeTexture order: +X, +Y, +Z, -X, -Y, -Z. */
  faces: [${sky.skyFaces.map((f) => `"${f}"`).join(", ")}],
  /** Multiply the sRGB-decoded sky faces by this to get back to panorama units. */
  skyScale: ${sky.skyScale},
  /** Unit vector pointing from the scene toward the sun. */
  sunDirection: ${tuple(sky.sunDirection)} as Vec3,
  sunColor: ${tuple(sky.sunColor)} as Vec3,
  /** DirectionalLight intensity matching the energy removed from the panorama (E_sun / π). */
  sunIntensity: ${sky.sunIntensity},
  sunElevationDeg: ${sky.sunElevationDeg},
  /** Sky-only horizontal irradiance / π (what a hemispheric fill light should approximate). */
  skyAmbient: ${sky.skyAmbient},
  /** Mean linear radiance of the sky just above the horizon (fog/haze color). */
  horizonColor: ${tuple(sky.horizonColor)} as Vec3,
  /** Radiance of the sun- and sky-lit ground that fills the panorama below the horizon. */
  groundRadiance: ${tuple(sky.groundRadiance)} as Vec3,
} as const;

/** Props and vegetation produced so far; \`PROP_MANIFEST\` in propAssets.ts fills the rest with placeholders. */
export const PROP_MANIFEST_GENERATED: Partial<Record<PropId, GeneratedPropAsset>> = {
${propsTs}
};
`;
  await writeFile(MANIFEST_TS, body);
  console.log(`wrote ${path.relative(process.cwd(), MANIFEST_TS)}`);
}

export async function reportSizes() {
  let total = 0;
  for (const dir of ["textures", "sky", "props"]) {
    let sum = 0;
    try {
      for (const file of await readdir(path.join(OUT_DIR, dir))) sum += (await stat(path.join(OUT_DIR, dir, file))).size;
    } catch {
      continue;
    }
    console.log(`${dir}/: ${(sum / 1e6).toFixed(2)} MB`);
    total += sum;
  }
  console.log(`total environment payload: ${(total / 1e6).toFixed(2)} MB`);
}
