// Generated by tools/map/osm/generate.ts; do not edit. Regenerate with:
//   node --experimental-transform-types tools/map/osm/generate.ts cz-holasovice
// Map data © OpenStreetMap contributors, ODbL 1.0 (openstreetmap.org/copyright), snapshot 2026-09-15T03:54:20Z.
// Elevation: AWS Terrain Tiles (terrarium), see apps/client/public/assets/map/credits.json.
import type { RealMapInfo } from "./types";

export const INFO: RealMapInfo = { id: "cz-holasovice", name: "Holašovice", country: "Czechia", countryCode: "cz", lat: 48.9697, lon: 14.2736, osmTimestamp: "2026-09-15T03:54:20Z", bakeUrl: "assets/map/cz-holasovice.terrain.bin", previewUrl: "assets/map/cz-holasovice.preview.svg", elevation: { mode: "real", scale: 1, realMin: 465.5, realMax: 523.7, relief: 47.5 }, stats: { pois: 10, buildings: 90, buildingCandidates: 139, spawns: 20, roadsKm: 5.62, waterHa: 1.1 }, credits: ["osm", "terrain-tiles", "eu-dem"] };
