// Generated by tools/map/build.ts --map cz-holasovice; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "c377a649",
  terrainChecksum: "95ef0045-99365750",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "fc9e4bcd",
  bytes: 2264209,
} as const;
