// Generated by tools/map/osm/generate.ts; do not edit. Real-world maps: small facts up front, map data loaded on demand.
import { INFO as CZ_HOLASOVICE } from "./cz-holasovice.info";
import { INFO as VN_CAMTHANH } from "./vn-camthanh.info";
import { INFO as JP_SHIRAKAWAGO } from "./jp-shirakawago.info";
import type { RealMapInfo, RealMapModule } from "./types";

export type { RealMapCreditId, RealMapInfo, RealMapModule } from "./types";

export interface RealMapEntry {
  readonly info: RealMapInfo;
  /** Loads the generated map module (a separate chunk in the client). */
  load(): Promise<RealMapModule>;
}

/** Generated real-world maps, recommended default first. */
export const REAL_MAPS: readonly RealMapEntry[] = [
  { info: CZ_HOLASOVICE, load: () => import("./cz-holasovice").then((m) => m.default) },
  { info: VN_CAMTHANH, load: () => import("./vn-camthanh").then((m) => m.default) },
  { info: JP_SHIRAKAWAGO, load: () => import("./jp-shirakawago").then((m) => m.default) },
];

export const DEFAULT_REAL_MAP_ID = "cz-holasovice";

export function findRealMap(id: string): RealMapEntry | undefined {
  return REAL_MAPS.find((entry) => entry.info.id === id);
}

export function loadRealMap(id: string): Promise<RealMapModule> {
  const entry = findRealMap(id);
  if (!entry) return Promise.reject(new Error(`Unknown real-world map "${id}" (known: ${REAL_MAPS.map((m) => m.info.id).join(", ")})`));
  return entry.load();
}
