// Generated by tools/map/build.ts --map jp-shirakawago; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "db3d62ed",
  terrainChecksum: "41496d67-2b7d2496",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "61345d9d",
  bytes: 2309311,
} as const;
