// Generated by tools/map/osm/generate.ts; do not edit. Regenerate with:
//   node --experimental-transform-types tools/map/osm/generate.ts jp-shirakawago
// Map data © OpenStreetMap contributors, ODbL 1.0 (openstreetmap.org/copyright), snapshot 2026-09-15T03:54:20Z.
// Elevation: AWS Terrain Tiles (terrarium), see apps/client/public/assets/map/credits.json.
import type { RealMapInfo } from "./types";

export const INFO: RealMapInfo = { id: "jp-shirakawago", name: "Shirakawa-gō", country: "Japan", countryCode: "jp", lat: 36.257, lon: 136.906, osmTimestamp: "2026-09-15T03:54:20Z", bakeUrl: "assets/map/jp-shirakawago.terrain.bin", previewUrl: "assets/map/jp-shirakawago.preview.svg", elevation: { mode: "real", scale: 0.3, realMin: 472.5, realMax: 680.3, relief: 51.6 }, stats: { pois: 11, buildings: 90, buildingCandidates: 274, spawns: 22, roadsKm: 7.39, waterHa: 3.5 }, credits: ["osm", "terrain-tiles"] };
