// Generated by tools/map/build.ts --map vn-camthanh; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "034b8a43",
  terrainChecksum: "c675de8f-3dad3c60",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "6199377e",
  bytes: 2431588,
} as const;
