// Generated by tools/map/osm/generate.ts; do not edit. Regenerate with:
//   node --experimental-transform-types tools/map/osm/generate.ts vn-camthanh
// Map data © OpenStreetMap contributors, ODbL 1.0 (openstreetmap.org/copyright), snapshot 2026-09-15T03:54:20Z.
// Elevation: AWS Terrain Tiles (terrarium), see apps/client/public/assets/map/credits.json.
import type { RealMapInfo } from "./types";

export const INFO: RealMapInfo = { id: "vn-camthanh", name: "Hội An – Cẩm Thanh", country: "Vietnam", countryCode: "vn", lat: 15.872, lon: 108.37, osmTimestamp: "2026-09-15T03:54:20Z", bakeUrl: "assets/map/vn-camthanh.terrain.bin", previewUrl: "assets/map/vn-camthanh.preview.svg", elevation: { mode: "flat", scale: 0, realMin: null, realMax: null, relief: 0 }, stats: { pois: 10, buildings: 90, buildingCandidates: 392, spawns: 20, roadsKm: 8.06, waterHa: 28.1 }, credits: ["osm"] };
