// Generated by tools/map/osm/generate.ts; do not edit. Regenerate with:
//   node --experimental-transform-types tools/map/osm/generate.ts vn-hangxanh
// Map data © OpenStreetMap contributors, ODbL 1.0 (openstreetmap.org/copyright), snapshot 2026-09-15T05:23:48Z.
// Elevation: AWS Terrain Tiles (terrarium), see apps/client/public/assets/map/credits.json.
import type { RealMapInfo } from "./types";

export const INFO: RealMapInfo = { id: "vn-hangxanh", name: "Ngã Tư Hàng Xanh", country: "Vietnam", countryCode: "vn", lat: 10.80144, lon: 106.71132, osmTimestamp: "2026-09-15T05:23:48Z", bakeUrl: "assets/map/vn-hangxanh.terrain.bin", previewUrl: "assets/map/vn-hangxanh.preview.svg", elevation: { mode: "flat", scale: 0, realMin: null, realMax: null, relief: 0 }, stats: { pois: 7, buildings: 110, buildingCandidates: 2139, spawns: 14, roadsKm: 9.6, waterHa: 0 }, credits: ["osm"] };
