// Generated by tools/map/build.ts --map vn-hangxanh; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "d8d2ab28",
  terrainChecksum: "d5f59cbb-5a47ee80",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "f717f9dd",
  bytes: 2520490,
} as const;
