// Generated by tools/map/build.ts --map vn-hangxanh; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "ea91ce20",
  terrainChecksum: "af3d8830-d64efedc",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "6bd3d745",
  bytes: 2489434,
} as const;
