// Generated by tools/map/build.ts --map vn-hangxanh; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "ee5fb689",
  terrainChecksum: "75a80366-5a47ee80",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "fec267c4",
  bytes: 2528043,
} as const;
