// Generated by tools/map/build.ts --map vn-phandangluu; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "4f40b5d6",
  terrainChecksum: "3758a6df-476f5aa2",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "1e972e44",
  bytes: 2563486,
} as const;
