// Generated by tools/map/build.ts --map vn-phandangluu; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "4a97cd9b",
  terrainChecksum: "26a0a2ed-8e3396f6",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "45b4c803",
  bytes: 2556624,
} as const;
