// Generated by tools/map/build.ts --map vn-phandangluu; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "a4dcb503",
  terrainChecksum: "182b2532-2c1bf238",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "30ad3148",
  bytes: 638453,
} as const;
