/**
 * Writes generated real-world map modules: `packages/shared/src/map/real/<id>.ts` (MapData and extras),
 * `<id>.info.ts` (picker facts) and the `index.ts` registry. Plain object literals, one list item per line, so diffs
 * between regenerations stay readable.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { ConvertResult } from "../../../packages/shared/src/map/real/convert/assemble.ts";
import type { PlaceConfig } from "../../../packages/shared/src/map/real/convert/types.ts";
import type { RealMapInfo } from "../../../packages/shared/src/map/real/types.ts";
import { REPO_ROOT } from "../lib/resolve.ts";

export const REAL_DIR = join(REPO_ROOT, "packages/shared/src/map/real");
const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** A JS literal for plain data: unquoted identifier keys, numbers as-is, `undefined` fields dropped. */
export function literal(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "number") return Object.is(value, -0) ? "0" : String(value);
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "boolean") return String(value);
  if (Array.isArray(value)) return `[${value.map(literal).join(", ")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined);
    if (entries.length === 0) return "{}";
    return `{ ${entries.map(([k, v]) => `${IDENTIFIER.test(k) ? k : JSON.stringify(k)}: ${literal(v)}`).join(", ")} }`;
  }
  throw new Error(`cannot emit ${typeof value}`);
}

function list(name: string, type: string, items: readonly unknown[], exported = false): string {
  const body = items.map((item) => `  ${literal(item)},`).join("\n");
  return `${exported ? "export " : ""}const ${name}: ${type} = [\n${body}\n];\n`;
}

/**
 * Scatter rules with their `exclude` polygons (POI cores, water, fence gaps: the same few shapes in every rule) moved
 * into one shared `ZONES` table.
 */
function scatterSource(rules: readonly { readonly exclude?: readonly (readonly (readonly [number, number])[])[] }[]): string {
  const zones: string[] = [];
  const index = new Map<string, number>();
  const lines = rules.map((rule) => {
    if (!rule.exclude || rule.exclude.length === 0) return `  ${literal(rule)},`;
    const refs = rule.exclude.map((polygon) => {
      const key = literal(polygon);
      if (!index.has(key)) {
        index.set(key, zones.length);
        zones.push(key);
      }
      return `ZONES[${index.get(key)}]!`;
    });
    const { exclude: _exclude, ...rest } = rule;
    const body = literal(rest);
    return `  ${body.slice(0, -2)}, exclude: [${refs.join(", ")}] },`;
  });
  return `/** Areas scatter rules leave empty: POI cores, woods, water, fence gaps. */
const ZONES: readonly (readonly Vec2Tuple[])[] = [
${zones.map((z) => `  ${z},`).join("\n")}
];

const SCATTERS: readonly ScatterRule[] = [
${lines.join("\n")}
];
`;
}

export function constName(id: string): string {
  return id.replace(/[^A-Za-z0-9]+/g, "_").toUpperCase();
}

export function infoFor(result: ConvertResult, config: PlaceConfig): RealMapInfo {
  const r = result.report;
  const eu = ["at", "be", "bg", "hr", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr", "hu", "ie", "it", "lv", "lt", "lu", "mt", "nl", "pl", "pt", "ro", "sk", "si", "es", "se"].includes(config.countryCode);
  return {
    id: config.id,
    name: config.name,
    country: config.country,
    countryCode: config.countryCode,
    lat: config.lat,
    lon: config.lon,
    osmTimestamp: r.osmTimestamp,
    bakeUrl: `assets/map/${config.id}.terrain.bin`,
    previewUrl: `assets/map/${config.id}.preview.svg`,
    elevation: { mode: r.elevation.mode, scale: r.elevation.scale, realMin: r.elevation.realMin, realMax: r.elevation.realMax, relief: r.elevation.gameRelief },
    stats: {
      pois: r.pois.count,
      buildings: r.buildings,
      buildingCandidates: r.placement.candidates,
      spawns: r.spawns,
      roadsKm: Math.round((r.roads.asphaltKm + r.roads.dirtKm) * 100) / 100,
      waterHa: r.landuse.waterHa,
    },
    credits: config.elevation.mode === "real" ? (eu ? ["osm", "terrain-tiles", "eu-dem"] : ["osm", "terrain-tiles"]) : ["osm"],
  };
}

export function writeRealMapModule(result: ConvertResult, config: PlaceConfig): { module: string; info: string } {
  const { parts } = result;
  const header = `// Generated by tools/map/osm/generate.ts; do not edit. Regenerate with:
//   node --experimental-transform-types tools/map/osm/generate.ts ${config.id}
// Map data © OpenStreetMap contributors, ODbL 1.0 (openstreetmap.org/copyright), snapshot ${result.report.osmTimestamp ?? "unknown"}.
// Elevation: AWS Terrain Tiles (terrarium), see apps/client/public/assets/map/credits.json.
`;
  const info = `${header}import type { RealMapInfo } from "./types";

export const INFO: RealMapInfo = ${literal(infoFor(result, config))};
`;
  const terrain = { ...parts.terrain, features: [] as unknown[] };
  const grid = parts.terrain.features.find((f) => f.kind === "heightGrid");
  const heightRows: string[] = [];
  if (grid && grid.kind === "heightGrid") for (let j = 0; j < grid.rows; j++) heightRows.push(`  ${grid.heights.slice(j * grid.columns, (j + 1) * grid.columns).join(", ")},`);
  const module = `${header}import { roadFlatten, type RoadSpec } from "../layout/roads";
import type { LayoutBuilding } from "../layout/buildings";
import type { ScatterRule } from "../layout/scatter";
import type { FlattenRegion, MapData, MapSpawn, PointOfInterest, TerrainSpec, Vec2Tuple } from "../types";
import { fenceOpenings, fenceProps, type FenceLine } from "./fences";
import { INFO } from "./${config.id}.info";
import type { RealMapModule } from "./types";

${grid && grid.kind === "heightGrid" ? `/** Real relief above the lowest playable point, m (${grid.columns} × ${grid.rows}, ${grid.spacing} m apart from the south-west corner). */\nconst HEIGHTS: readonly number[] = [\n${heightRows.join("\n")}\n];\n\n` : ""}const TERRAIN: TerrainSpec = {
  ...${literal(terrain)},
  features: [${grid && grid.kind === "heightGrid" ? `{ kind: "heightGrid", origin: ${literal(grid.origin)}, spacing: ${grid.spacing}, columns: ${grid.columns}, rows: ${grid.rows}, heights: HEIGHTS }` : ""}],
};

/** One pad per building (terraced where neighbours sit level). */
${list("PADS", "readonly FlattenRegion[]", parts.pads)}
/** Streams and ditches as dry creek beds. */
${list("CREEKS", "readonly FlattenRegion[]", parts.creeks)}
${list("ROADS", "readonly RoadSpec[]", parts.roads, true)}
${list("POIS", "readonly PointOfInterest[]", parts.pois)}
${list("BUILDINGS", "readonly LayoutBuilding[]", parts.buildings)}
/** Water outlines: fenced, not walkable. */
${list("WATER", "readonly (readonly Vec2Tuple[])[]", result.water, true)}
/** Water-edge fences (gaps where roads cross) and railings where roads cross water. */
${list("FENCES", "readonly FenceLine[]", parts.fences)}
${scatterSource(parts.scatters)}
${list("SPAWNS", "readonly MapSpawn[]", parts.spawns)}
export const OPENINGS = fenceOpenings(FENCES);

export const MAP: MapData = {
  id: ${literal(config.id)},
  name: ${literal(config.name)},
  terrain: TERRAIN,
  flatten: [...PADS, ...CREEKS, ...ROADS.map(roadFlatten)],
  bounds: ${literal(result.map.bounds)},
  pois: POIS,
  buildings: BUILDINGS,
  props: fenceProps(FENCES),
  scatters: SCATTERS,
  spawns: SPAWNS,
};

const MODULE: RealMapModule = {
  info: INFO,
  map: MAP,
  roads: ROADS,
  water: WATER,
  openings: OPENINGS,
  validation: { ...${literal({ poiSpacing: result.validation.poiSpacing, minorPoiSpacing: result.validation.minorPoiSpacing, minorPoiRadius: result.validation.minorPoiRadius, buildingGap: result.validation.buildingGap })}, openings: OPENINGS },
};
export default MODULE;
`;
  writeFileSync(join(REAL_DIR, `${config.id}.info.ts`), info);
  writeFileSync(join(REAL_DIR, `${config.id}.ts`), module);
  writeRegistry();
  return { module, info };
}

/** Regenerates `real/index.ts` from the `*.info.ts` files present. */
export function writeRegistry(): void {
  const ids = readdirSync(REAL_DIR)
    .filter((f) => f.endsWith(".info.ts"))
    .map((f) => f.slice(0, -".info.ts".length))
    .filter((id) => existsSync(join(REAL_DIR, `${id}.ts`)))
    .sort(registryOrder);
  const imports = ids.map((id) => `import { INFO as ${constName(id)} } from "./${id}.info";`).join("\n");
  const entries = ids.map((id) => `  { info: ${constName(id)}, load: () => import("./${id}").then((m) => m.default) },`).join("\n");
  const source = `// Generated by tools/map/osm/generate.ts; do not edit. Real-world maps: small facts up front, map data loaded on demand.
${imports}
import type { RealMapInfo, RealMapModule } from "./types";

export type { RealMapCreditId, RealMapInfo, RealMapModule } from "./types";

export interface RealMapEntry {
  readonly info: RealMapInfo;
  /** Loads the generated map module (a separate chunk in the client). */
  load(): Promise<RealMapModule>;
}

/** Generated real-world maps, recommended default first. */
export const REAL_MAPS: readonly RealMapEntry[] = [
${entries}
];

export const DEFAULT_REAL_MAP_ID = ${JSON.stringify(ids[0] ?? "")};

export function findRealMap(id: string): RealMapEntry | undefined {
  return REAL_MAPS.find((entry) => entry.info.id === id);
}

export function loadRealMap(id: string): Promise<RealMapModule> {
  const entry = findRealMap(id);
  if (!entry) return Promise.reject(new Error(\`Unknown real-world map "\${id}" (known: \${REAL_MAPS.map((m) => m.info.id).join(", ")})\`));
  return entry.load();
}
`;
  const path = join(REAL_DIR, "index.ts");
  if (!existsSync(path) || readFileSync(path, "utf8") !== source) writeFileSync(path, source);
}

/** Presets keep their order in places.ts (Holašovice first); custom places follow alphabetically. */
function registryOrder(a: string, b: string): number {
  const preset = ["cz-holasovice", "vn-camthanh", "jp-shirakawago"];
  const ia = preset.indexOf(a);
  const ib = preset.indexOf(b);
  if (ia >= 0 || ib >= 0) return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib);
  return a < b ? -1 : 1;
}
