/**
 * Generates a real-world map from OpenStreetMap and elevation data, then bakes it.
 *
 *   node --experimental-transform-types tools/map/osm/generate.ts <placeId> [--no-nav] [--no-build]
 *   node --experimental-transform-types tools/map/osm/generate.ts --lat 49.0 --lon 14.3 --name "Some Village" \
 *        [--id cz-some-village] [--country Czechia --cc cz] [--flat | --scale 0.5] [--max-relief 50] [--tropical]
 *
 * 1. Fetches (or reads the cache in assets-src/map/osm/<id>/) the Overpass data and DEM tiles (fetch.ts).
 * 2. Converts them with the pure converter (packages/shared/src/map/real/convert), which fixes the layout until it
 *    validates and every POI, spawn and door is reachable on the nav grid.
 * 3. Writes packages/shared/src/map/real/<id>.ts, <id>.info.ts and the index.ts registry.
 * 4. Runs tools/map/build.ts --map <id> (terrain bake, checksum record, docs/map/<id>.svg, preview SVG).
 *
 * A custom --lat/--lon place is appended to places.ts, so it can be regenerated by id later. Exits 1 when the result
 * still has validation issues or unreachable probes. Self-terminates after 15 minutes.
 */
import "../lib/resolve.ts";
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PlaceConfig } from "../../../packages/shared/src/map/real/convert/types.ts";
import { REPO_ROOT } from "../lib/resolve.ts";

setTimeout(() => {
  console.error("[osm] watchdog: generation took longer than 15 minutes");
  process.exit(2);
}, 900_000).unref();

const { findPlace, PLACES } = await import("./places.ts");
const { fetchPlace } = await import("./fetch.ts");
const { sampleElevation } = await import("./dem.ts");
const { writeRealMapModule, literal } = await import("./emit.ts");
const { createProjection } = await import("../../../packages/shared/src/map/real/convert/projection.ts");
const { convertRealMap } = await import("../../../packages/shared/src/map/real/convert/assemble.ts");

const args = process.argv.slice(2);
const flag = (name: string) => args.includes(`--${name}`);
const option = (name: string): string | undefined => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : undefined;
};

function slug(text: string): string {
  return text
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "D")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function customPlace(): PlaceConfig {
  const lat = Number(option("lat"));
  const lon = Number(option("lon"));
  const name = option("name");
  if (!Number.isFinite(lat) || !Number.isFinite(lon) || Math.abs(lat) > 85 || Math.abs(lon) > 180 || !name) {
    console.error("usage: generate.ts <placeId> | --lat <deg> --lon <deg> --name <display name> [--id <id>] [--country <name> --cc <iso2>] [--flat | --scale <0..1>] [--max-relief <m>] [--tropical]");
    console.error(`known places: ${PLACES.map((p) => p.id).join(", ")}`);
    process.exit(1);
  }
  const cc = (option("cc") ?? "xx").toLowerCase();
  const id = option("id") ?? `${cc === "xx" ? "custom" : cc}-${slug(name) || "place"}`;
  if (!/^[a-z0-9][a-z0-9-]{1,48}$/.test(id)) {
    console.error(`[osm] invalid id "${id}": use lowercase letters, digits and dashes`);
    process.exit(1);
  }
  const scale = Number(option("scale") ?? "1");
  return {
    id,
    name,
    country: option("country") ?? "",
    countryCode: cc,
    lat: Math.round(lat * 1e5) / 1e5,
    lon: Math.round(lon * 1e5) / 1e5,
    elevation: { mode: flag("flat") ? "flat" : "real", scale: Number.isFinite(scale) && scale > 0 ? Math.min(1, scale) : 1, maxRelief: Number(option("max-relief") ?? "55") },
    climate: flag("tropical") ? "tropical" : "temperate",
  };
}

/** Appends a custom place between the markers in places.ts (unless one with that id exists). */
function rememberPlace(place: PlaceConfig): void {
  if (findPlace(place.id)) return;
  const path = join(REPO_ROOT, "tools/map/osm/places.ts");
  const source = readFileSync(path, "utf8");
  const marker = "  // </custom-places>";
  if (!source.includes(marker)) throw new Error("places.ts lost its custom-places marker");
  const entry = `  ${literal(place)},\n`;
  writeFileSync(path, source.replace(marker, `${entry}${marker}`));
  console.info(`[osm] added "${place.id}" to tools/map/osm/places.ts`);
}

const positional = args[0] && !args[0].startsWith("--") ? args[0] : undefined;
const place = positional ? findPlace(positional) : option("lat") ? customPlace() : undefined;
if (!place) {
  console.error(`[osm] unknown place "${positional ?? ""}" (known: ${PLACES.map((p) => p.id).join(", ")}); or pass --lat --lon --name`);
  process.exit(1);
}

const started = performance.now();
const elapsed = () => `${((performance.now() - started) / 1000).toFixed(1)} s`;
const fetched = await fetchPlace(place);
if (!positional) rememberPlace(place);
const projection = createProjection(place.lat, place.lon);
const elevation = place.elevation.mode === "real" ? await sampleElevation(fetched.tiles, projection, 640, 10) : null;
const result = convertRealMap({ osm: fetched.osm, elevation, config: place }, { navCheck: !flag("no-nav"), log: (message) => console.info(`[osm] ${elapsed()} ${message}`) });
writeRealMapModule(result, place);

const r = result.report;
console.info(`[osm] ${place.id}: wrote packages/shared/src/map/real/${place.id}.ts (${elapsed()})`);
console.info(
  JSON.stringify(
    {
      buildings: { kept: r.buildings, candidates: r.placement.candidates, droppedConflicts: r.placement.droppedConflicts, droppedCap: r.placement.droppedCap, droppedByValidation: r.droppedByValidation, pushedBack: r.placement.pushedBack, byPrefab: r.buildingsByPrefab },
      pois: r.pois,
      poiNames: result.map.pois.map((p) => `${p.name} (${p.kind}, tier ${p.lootTier})`),
      spawns: r.spawns,
      roads: r.roads,
      elevation: r.elevation,
      landuse: r.landuse,
      waterFenceMeters: r.waterFenceMeters,
      iterations: r.iterations,
      issues: r.issues.length,
      reachability: r.reachability,
      layoutChecksum: r.layoutChecksum,
    },
    null,
    2,
  ),
);
const reach = r.reachability;
const unreachable = reach && [reach.pois, reach.spawns, reach.entrances].some((s) => s.split("/")[0] !== s.split("/")[1]);
let failed = r.issues.length > 0 || Boolean(unreachable) || (reach !== null && reach.lootRatio < 0.97);
if (failed) console.error(`[osm] ${place.id}: ${r.issues.length} validation issues, reachability ${JSON.stringify(reach)}`);

if (!flag("no-build")) {
  // A fresh process imports the module just written, so the bake is built from exactly what the game loads.
  const build = spawnSync(process.execPath, ["--experimental-transform-types", "--no-warnings", join(REPO_ROOT, "tools/map/build.ts"), "--map", place.id], { stdio: "inherit" });
  if (build.status !== 0) failed = true;
  const record = readFileSync(join(REPO_ROOT, `packages/shared/src/map/real/${place.id}.bake.ts`), "utf8");
  if (!record.includes(`layoutChecksum: "${r.layoutChecksum}"`)) {
    console.error(`[osm] ${place.id}: the written module builds layout ${/layoutChecksum: "(\w+)"/.exec(record)?.[1]}, the converter built ${r.layoutChecksum}`);
    failed = true;
  }
}
process.exit(failed ? 1 : 0);
