import type { BotDifficulty, BotProfile } from "../types";

// Difficulty table (docs/bots/design.md §6). Numbers are first-pass tuning; revisit after headless duel and full-match
// runs against the §6 hit-rate targets.

const EASY: BotProfile = {
  difficulty: "easy",
  perception: {
    fovDegrees: 90,
    peripheralFactor: 0.25,
    spotRangeMeters: 140,
    awarenessPerSecond: 1.2,
    proximityMeters: 3,
    reactionSeconds: [0.45, 0.7],
    hearingScale: 0.6,
    noiseErrorFraction: 0.25,
    forgetSeconds: 8,
  },
  aim: {
    maxTurnRateDeg: 180,
    acquireSeconds: 0.55,
    acquireErrorDeg: 9,
    trackingNoiseDeg: 1.8,
    trackingNoiseHz: 1.2,
    velocityErrorScale: 0.12,
    leadAccuracy: 0.4,
    dropAccuracy: 0.3,
    recoilCompensation: 0.3,
    recoilDelaySeconds: 0.25,
    firstShotDelaySeconds: 0.35,
    fireToleranceScale: 3,
    aimPoint: "chest",
    flinchDeg: 4,
  },
  fire: {
    closeMeters: 20,
    midMeters: 60,
    burstClose: [6, 12],
    burstMid: [3, 5],
    burstLong: [1, 2],
    burstPauseSeconds: [0.5, 0.9],
    hipFireMeters: 6,
    maxRange: { rifle: 110, pistol: 35, shotgun: 15, sniper: 150 },
    smokeSuppressChance: 0,
    smokeSuppressSeconds: 0,
  },
  tactics: {
    strafeChance: 0.25,
    strafeIntervalSeconds: [1, 1.6],
    coverChance: 0.35,
    peekSeconds: [1.5, 2.5],
    grenadeChance: 0.1,
    grenadeCooldownSeconds: 40,
    smokeReviveChance: 0,
    flashDodgeChance: 0,
    fleeHealth: 20,
    healSafeSeconds: 4,
    zoneMarginSeconds: 5,
    chaseSeconds: 4,
    reviveRisk: 0.8,
  },
};

const NORMAL: BotProfile = {
  difficulty: "normal",
  perception: {
    fovDegrees: 110,
    peripheralFactor: 0.4,
    spotRangeMeters: 220,
    awarenessPerSecond: 2.2,
    proximityMeters: 5,
    reactionSeconds: [0.28, 0.42],
    hearingScale: 1,
    noiseErrorFraction: 0.15,
    forgetSeconds: 15,
  },
  aim: {
    maxTurnRateDeg: 320,
    acquireSeconds: 0.32,
    acquireErrorDeg: 6,
    trackingNoiseDeg: 0.9,
    trackingNoiseHz: 1.6,
    velocityErrorScale: 0.07,
    leadAccuracy: 0.75,
    dropAccuracy: 0.7,
    recoilCompensation: 0.6,
    recoilDelaySeconds: 0.15,
    firstShotDelaySeconds: 0.2,
    fireToleranceScale: 2,
    aimPoint: "upperChest",
    flinchDeg: 3,
  },
  fire: {
    closeMeters: 25,
    midMeters: 80,
    burstClose: [8, 15],
    burstMid: [3, 6],
    burstLong: [1, 3],
    burstPauseSeconds: [0.3, 0.6],
    hipFireMeters: 8,
    maxRange: { rifle: 180, pistol: 45, shotgun: 18, sniper: 350 },
    smokeSuppressChance: 0.3,
    smokeSuppressSeconds: 1,
  },
  tactics: {
    strafeChance: 0.55,
    strafeIntervalSeconds: [0.6, 1.1],
    coverChance: 0.7,
    peekSeconds: [1, 1.8],
    grenadeChance: 0.3,
    grenadeCooldownSeconds: 25,
    smokeReviveChance: 0.4,
    flashDodgeChance: 0.3,
    fleeHealth: 35,
    healSafeSeconds: 6,
    zoneMarginSeconds: 20,
    chaseSeconds: 8,
    reviveRisk: 0.5,
  },
};

const HARD: BotProfile = {
  difficulty: "hard",
  perception: {
    fovDegrees: 130,
    peripheralFactor: 0.6,
    spotRangeMeters: 320,
    awarenessPerSecond: 3.5,
    proximityMeters: 8,
    reactionSeconds: [0.16, 0.26],
    hearingScale: 1.2,
    noiseErrorFraction: 0.08,
    forgetSeconds: 25,
  },
  aim: {
    maxTurnRateDeg: 520,
    acquireSeconds: 0.18,
    acquireErrorDeg: 3.5,
    trackingNoiseDeg: 0.45,
    trackingNoiseHz: 2,
    velocityErrorScale: 0.035,
    leadAccuracy: 0.95,
    dropAccuracy: 0.95,
    recoilCompensation: 0.85,
    recoilDelaySeconds: 0.08,
    firstShotDelaySeconds: 0.1,
    fireToleranceScale: 1.4,
    aimPoint: "neck",
    flinchDeg: 2,
  },
  fire: {
    closeMeters: 30,
    midMeters: 100,
    burstClose: [10, 30],
    burstMid: [4, 8],
    burstLong: [2, 4],
    burstPauseSeconds: [0.2, 0.4],
    hipFireMeters: 10,
    maxRange: { rifle: 260, pistol: 60, shotgun: 22, sniper: 500 },
    smokeSuppressChance: 0.6,
    smokeSuppressSeconds: 1.5,
  },
  tactics: {
    strafeChance: 0.85,
    strafeIntervalSeconds: [0.35, 0.7],
    coverChance: 0.95,
    peekSeconds: [0.6, 1.2],
    grenadeChance: 0.5,
    grenadeCooldownSeconds: 15,
    smokeReviveChance: 0.8,
    flashDodgeChance: 0.7,
    fleeHealth: 45,
    healSafeSeconds: 8,
    zoneMarginSeconds: 35,
    chaseSeconds: 12,
    reviveRisk: 0.3,
  },
};

export const BOT_PROFILES: Readonly<Record<BotDifficulty, BotProfile>> = { easy: EASY, normal: NORMAL, hard: HARD };

export function botProfile(difficulty: BotDifficulty): BotProfile {
  return BOT_PROFILES[difficulty];
}
