/**
 * Typed mirror of `public/assets/equipment/manifest.json`, generated by `node tools/assets/equipment.ts`. Kept separate
 * from the weapon/character manifest so the equipment art is optional: when the file or a model is missing, the game
 * falls back to the procedural equipment meshes.
 *
 * Conventions match manifest.ts: meters, Babylon left-handed space relative to the instance root, inclusive source
 * frames. Item space: +Y up (a grenade's fuse axis), +Z the item's front, origin at the body's bounding-box centre.
 */
import type { Bounds, Credit, FrameRange, MeshStats, Vec3 } from "./manifest";

export const EQUIPMENT_MODEL_IDS = [
  "frag",
  "smoke",
  "flash",
  "molotov",
  "bandage",
  "first_aid",
  "medkit",
  "energy_drink",
  "painkiller",
  "helmet",
  "vest",
  "backpack",
  "ammo_can",
] as const;
export type EquipmentModelId = (typeof EQUIPMENT_MODEL_IDS)[number];

/** Separately movable parts. `body` is everything else; `ring` is the pull ring together with its pin. */
export type EquipmentPartRole = "body" | "spoon" | "ring";

export interface EquipmentAsset {
  /** Relative to the equipment manifest URL's parent (the assets directory), like manifest.ts urls. */
  readonly url: string;
  readonly hash: string;
  readonly bytes: number;
  /** glTF node names; parts are direct children of the file's single root node, each origin at the part's centre. */
  readonly nodes: Readonly<Partial<Record<EquipmentPartRole, string>>> & { readonly root: string; readonly body: string };
  /** All parts at rest. */
  readonly bounds: Bounds;
  /** Body only (no pin, ring or spoon), e.g. for a thrown grenade's rolling radius. */
  readonly bodyBounds: Bounds;
  readonly stats: MeshStats;
  readonly credit: string;
}

/** Throw clip phases cut from the single baked "throw" animation. */
export type ThrowArmsClipName = "ready" | "windup" | "throw" | "follow" | "recover";

export type ThrowArmsNodeRole =
  /** Skinned arms mesh. */
  | "arms"
  | "rightShoulder"
  | "rightHand"
  | "leftShoulder"
  | "leftHand"
  /** Empty node under the right wrist where a held item's origin goes (+Y fuse axis up out of the fist). */
  | "grip";

export interface ThrowArmsAsset {
  readonly url: string;
  readonly hash: string;
  readonly bytes: number;
  readonly fps: number;
  /** The single AnimationGroup holding every clip. */
  readonly animation: string;
  readonly lastFrame: number;
  readonly clips: Readonly<Record<ThrowArmsClipName, FrameRange>>;
  /** Source frame (fractional) where the fingers open and the item leaves the hand. */
  readonly releaseFrame: number;
  readonly nodes: Readonly<Record<ThrowArmsNodeRole, string>>;
  /** Positions at the ready frame. */
  readonly anchors: { readonly grip: Vec3; readonly leftHand: Vec3; readonly rightHand: Vec3 };
  readonly bounds: Bounds;
  readonly stats: MeshStats;
  readonly credit: string;
}

export interface EquipmentManifest {
  readonly version: 1;
  readonly arms: ThrowArmsAsset | null;
  readonly items: Readonly<Partial<Record<EquipmentModelId, EquipmentAsset>>>;
  readonly credits: readonly Credit[];
}
