/**
 * Typed mirror of `public/assets/manifest.json`, generated by `pnpm assets` (tools/assets/build.ts).
 * The build script type-checks its output against these types, so this file is the contract.
 *
 * Conventions:
 * - Distances are meters. Positions/bounds are in Babylon's left-handed space relative to the
 *   instance root (+Y up, +Z forward; the glTF loader mirrors X), i.e. what `getAbsolutePosition()`
 *   returns for an instance whose root sits at the origin with identity rotation.
 * - Weapon clip frames are inclusive source frames at `fps` (both ends playable).
 */

export type Vec3 = readonly [x: number, y: number, z: number];
export type FrameRange = readonly [startFrame: number, endFrame: number];

export interface Bounds {
  readonly min: Vec3;
  readonly max: Vec3;
}

export interface MeshStats {
  readonly vertices: number;
  readonly triangles: number;
  readonly textures: number;
  /** Texture container used for all textures in the file. */
  readonly textureFormat: "ktx2" | "webp";
}

export const WEAPON_IDS = ["rifle", "shotgun", "pistol", "sniper"] as const;
export type WeaponId = (typeof WEAPON_IDS)[number];

export const CHARACTER_IDS = ["swat"] as const;
export type CharacterId = (typeof CHARACTER_IDS)[number];

/** Clip names shared by all weapons. Optional ones only exist where the source animation has them. */
export type WeaponClipName =
  | "idle"
  | "fire"
  | "fireLast"
  | "reload"
  | "reloadEmpty"
  /** Shotgun shell-by-shell reload: start → insert (repeat per shell, loops seamlessly) → end. */
  | "reloadStart"
  | "reloadInsert"
  | "reloadEnd"
  | "bolt"
  | "pump"
  | "hide"
  | "ready"
  | "melee";

export type WeaponNodeRole =
  /** Animated gun root; attach weapon-local effects here. */
  | "body"
  /** Skinned first-person arms mesh. */
  | "arms"
  /** Empty node added by the pipeline at the barrel tip (child of `body`). */
  | "muzzle"
  /** Empty node added by the pipeline at the ejection port (child of `body`). */
  | "ejection"
  | "mag"
  | "bolt"
  | "chargingHandle"
  | "slide"
  | "pump"
  /** Loose round/shell that is animated in reload/pump clips. */
  | "shell"
  | "trigger"
  | "scope"
  | "scopeLens"
  | "reticle";

export interface WeaponAsset {
  /** Relative to the manifest URL. */
  readonly url: string;
  /** Content hash; appended as a query string for cache busting. */
  readonly hash: string;
  readonly bytes: number;
  /** Frame rate of the source animation and of `clips`. */
  readonly fps: number;
  /** Name of the single AnimationGroup that contains every clip. */
  readonly animation: string;
  /** Last frame of the baked animation. */
  readonly lastFrame: number;
  readonly clips: Readonly<Partial<Record<WeaponClipName, FrameRange>>>;
  /** glTF node names (unique within the asset). */
  readonly nodes: Readonly<Partial<Record<WeaponNodeRole, string>>> & {
    readonly body: string;
    readonly arms: string;
    readonly muzzle: string;
    readonly ejection: string;
  };
  /** Rest positions of selected nodes at the first idle frame. */
  readonly anchors: {
    readonly muzzle: Vec3;
    readonly ejection: Vec3;
    readonly scopeLens?: Vec3;
  };
  /** Whole asset (arms + gun) at the first idle frame. */
  readonly bounds: Bounds;
  readonly stats: MeshStats;
  /** Key into `AssetManifest.credits`. */
  readonly credit: string;
}

export type CharacterClipName =
  | "rifle_idle"
  | "walk_fwd"
  | "walk_back"
  | "walk_left"
  | "walk_right"
  | "crouch_walk_fwd"
  | "run_fwd"
  | "run_back"
  | "run_left"
  | "run_right"
  | "sprint_fwd"
  | "crouch_idle"
  | "jump_up"
  | "jump_loop"
  | "jump_down"
  | "fire"
  | "reload"
  | "hit"
  | "death_front"
  | "death_back"
  /**
   * Knocked (DBNO), revive, item-use, throw and loot clips. Every lying clip shares one convention: hips over the root
   * origin, head toward −Z (so `crawl` moves toward −Z), feet toward +Z.
   */
  | "knock_down"
  | "writhe"
  | "crawl"
  | "get_up"
  | "cpr_give"
  | "cpr_receive"
  | "heal_kneel"
  | "bandage"
  | "drink"
  | "throw_stand"
  | "throw_crouch"
  | "pick_up";

export type CharacterBoneRole =
  | "hips"
  | "spine"
  | "chest"
  | "neck"
  | "head"
  | "leftUpperArm"
  | "leftForeArm"
  | "leftHand"
  | "rightUpperArm"
  | "rightForeArm"
  | "rightHand"
  | "leftUpLeg"
  | "leftLeg"
  | "leftFoot"
  | "rightUpLeg"
  | "rightLeg"
  | "rightFoot";

export interface CharacterClip {
  /** Seconds. */
  readonly duration: number;
  readonly loop: boolean;
  /**
   * Horizontal root motion that the pipeline removed from the hips (m/s, Babylon space, character facing +Z).
   * Use it to match playback speed to movement speed: `speedRatio = actualSpeed / |rootMotion|`.
   */
  readonly rootMotion?: Vec3;
}

export interface CharacterAsset {
  readonly url: string;
  readonly hash: string;
  readonly bytes: number;
  /** Standing height in bind pose (meters). Feet at y = 0, facing +Z. */
  readonly height: number;
  readonly bounds: Bounds;
  readonly clips: Readonly<Record<CharacterClipName, CharacterClip>>;
  /** Bone/TransformNode names for hitboxes and weapon attachment. */
  readonly bones: Readonly<Record<CharacterBoneRole, string>>;
  readonly stats: MeshStats;
  readonly credit: string;
}

export interface Credit {
  readonly id: string;
  readonly title: string;
  readonly author: string;
  readonly authorUrl?: string;
  readonly url: string;
  readonly license: string;
  readonly licenseUrl?: string;
  /** False for sources that don't require attribution (listed for completeness). */
  readonly attributionRequired: boolean;
  readonly notes?: string;
}

export interface DecoderUrls {
  /** Classic script defining `MeshoptDecoder`. */
  readonly meshopt: string;
  /** Babylon KTX2 decoder worker module plus its wasm transcoders. */
  readonly ktx2: {
    readonly jsDecoderModule: string;
    readonly jsMSCTranscoder: string;
    readonly wasmMSCTranscoder: string;
    readonly wasmUASTCToASTC: string;
    readonly wasmUASTCToBC7: string;
    readonly wasmUASTCToRGBA_UNORM: string;
    readonly wasmUASTCToRGBA_SRGB: string;
    readonly wasmUASTCToR8_UNORM: string;
    readonly wasmUASTCToRG8_UNORM: string;
    readonly wasmZSTDDecoder: string;
  };
}

export interface AssetManifest {
  readonly version: 1;
  readonly weapons: Readonly<Record<WeaponId, WeaponAsset>>;
  readonly characters: Readonly<Record<CharacterId, CharacterAsset>>;
  readonly credits: readonly Credit[];
  /** Relative to the manifest URL. */
  readonly decoders: DecoderUrls;
}
