/**
 * Map build step: validates the layout, bakes the terrain binary the client loads, records the bake and layout
 * checksums for the tests, and regenerates the overview SVG and the small preview SVG menus show.
 *
 *   node --experimental-transform-types tools/map/build.ts [--map v1|<realMapId>|all] [--check]
 *
 * Outputs for Map v1 (the default):
 *   apps/client/public/assets/map/mapV1.terrain.bin     terrain heights + surface mask + paint (see terrain/bake.ts)
 *   packages/shared/src/map/layout/mapV1Bake.ts         inputs hash and checksums (asserted by mapV1.test.ts)
 *   docs/map/mapV1.svg                                  overview map
 *   apps/client/public/assets/map/mapV1.preview.svg     picker preview
 * Outputs for the maze (`--map mazebr`):
 *   apps/client/public/assets/map/mazebr.terrain.bin, packages/shared/src/map/mazeBrBake.ts, docs/map/mazebr.svg,
 *   apps/client/public/assets/map/mazebr.preview.svg
 * Outputs for a real-world map `<id>` (generated by tools/map/osm/generate.ts):
 *   apps/client/public/assets/map/<id>.terrain.bin, packages/shared/src/map/real/<id>.bake.ts, docs/map/<id>.svg,
 *   apps/client/public/assets/map/<id>.preview.svg
 * `--check` builds and validates without writing anything; exits 1 when outputs are stale or the layout has issues.
 */
import "./lib/resolve.ts";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { REPO_ROOT } from "./lib/resolve.ts";

setTimeout(() => {
  console.error("[map] watchdog: took longer than 5 minutes");
  process.exit(2);
}, 300_000).unref();

const shared = await import("@twobullets/shared");
const { MAP_V1, MAZE_BR, MAZE_BR_VALIDATION, buildTerrain, buildMapLayout, validateMapLayout, encodeTerrainBake, terrainInputsHash, renderMapOverviewSvg, INSTANCE_STRIDE } = shared;
const { getMapProp, rectCorners, getBuildingPrefab, isBuildingPrefabId } = shared;
const { REAL_MAPS, loadRealMap } = await import("../../packages/shared/src/map/real/index.ts");
const { renderMapPreviewSvg } = await import("../../packages/shared/src/map/real/preview.ts");
const { prefabRectOf } = await import("../../packages/shared/src/map/real/previewGeometry.ts");
type MapData = import("@twobullets/shared").MapData;
type ValidationOptions = import("@twobullets/shared").ValidationOptions;
type MapLayout = import("@twobullets/shared").MapLayout;

const check = process.argv.includes("--check");
const mapIndex = process.argv.indexOf("--map");
const mapArg = mapIndex >= 0 ? (process.argv[mapIndex + 1] ?? "v1") : "v1";
const ids = mapArg === "all" ? ["v1", MAZE_BR.id, ...REAL_MAPS.map((m) => m.info.id)] : [mapArg];

interface Target {
  readonly map: MapData;
  readonly validation?: ValidationOptions;
  readonly water?: readonly (readonly [number, number])[][];
  readonly outputs: { readonly bake: string; readonly record: string; readonly svg: string; readonly preview: string };
  readonly record: (inputsHash: string, terrainChecksum: string, layoutChecksum: string, bytes: number) => string;
  /** Overrides the default picker preview (which draws woods, water, roads and roofs — none of which a maze has). */
  readonly preview?: (map: MapData, layout: MapLayout) => string;
}

async function target(id: string): Promise<Target> {
  if (id === "v1") {
    return {
      map: MAP_V1,
      outputs: {
        bake: join(REPO_ROOT, "apps/client/public/assets/map/mapV1.terrain.bin"),
        record: join(REPO_ROOT, "packages/shared/src/map/layout/mapV1Bake.ts"),
        svg: join(REPO_ROOT, "docs/map/mapV1.svg"),
        preview: join(REPO_ROOT, "apps/client/public/assets/map/mapV1.preview.svg"),
      },
      record: (inputsHash, terrainChecksum, layoutChecksum, bytes) => `// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${inputsHash}",
  terrainChecksum: "${terrainChecksum}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layoutChecksum}",
  bytes: ${bytes},
} as const;
`,
    };
  }
  if (id === MAZE_BR.id) {
    return {
      map: MAZE_BR,
      validation: MAZE_BR_VALIDATION,
      preview: mazePreviewSvg,
      outputs: {
        bake: join(REPO_ROOT, `apps/client/public/assets/map/${MAZE_BR.id}.terrain.bin`),
        record: join(REPO_ROOT, "packages/shared/src/map/mazeBrBake.ts"),
        svg: join(REPO_ROOT, `docs/map/${MAZE_BR.id}.svg`),
        preview: join(REPO_ROOT, `apps/client/public/assets/map/${MAZE_BR.id}.preview.svg`),
      },
      record: (inputsHash, terrainChecksum, layoutChecksum, bytes) => `// Generated by tools/map/build.ts --map ${MAZE_BR.id}; do not edit. Rebuild after changing the maze terrain, flatten regions or walls.
export const MAZE_BR_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${inputsHash}",
  terrainChecksum: "${terrainChecksum}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layoutChecksum}",
  bytes: ${bytes},
} as const;
`,
    };
  }
  const module = await loadRealMap(id);
  return {
    map: module.map,
    validation: module.validation,
    water: module.water as (readonly [number, number])[][],
    outputs: {
      bake: join(REPO_ROOT, `apps/client/public/assets/map/${id}.terrain.bin`),
      record: join(REPO_ROOT, `packages/shared/src/map/real/${id}.bake.ts`),
      svg: join(REPO_ROOT, `docs/map/${id}.svg`),
      preview: join(REPO_ROOT, `apps/client/public/assets/map/${id}.preview.svg`),
    },
    record: (inputsHash, terrainChecksum, layoutChecksum, bytes) => `// Generated by tools/map/build.ts --map ${id}; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${inputsHash}",
  terrainChecksum: "${terrainChecksum}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layoutChecksum}",
  bytes: ${bytes},
} as const;
`,
  };
}

let failed = false;
for (const id of ids) {
  const { map, validation, water, outputs, record: recordFor, preview: previewSvg } = await target(id);
  let started = performance.now();
  const terrain = buildTerrain(map.terrain, map.flatten);
  const terrainMs = performance.now() - started;
  started = performance.now();
  const layout = buildMapLayout(map, terrain);
  const layoutMs = performance.now() - started;
  console.info(`[map] ${id}: terrain ${terrainMs.toFixed(0)} ms (checksum ${terrain.checksum()}), layout ${layoutMs.toFixed(0)} ms (checksum ${layout.checksum})`);

  const issues = validateMapLayout(map, terrain, layout, validation);
  for (const issue of issues) console.warn(`[map] ${issue.kind}: ${issue.message}`);

  const bake = await encodeTerrainBake(terrain, map.flatten);
  const record = recordFor(terrainInputsHash(map.terrain, map.flatten), terrain.checksum(), layout.checksum, bake.length);
  const svg = renderMapOverviewSvg(map, terrain, layout);
  const preview = previewSvg ? previewSvg(map, layout) : renderMapPreviewSvg(map, water ? { water } : {});

  if (check) {
    const stale = [
      [outputs.record, record],
      [outputs.svg, svg],
      [outputs.preview, preview],
    ].filter(([path, content]) => readOrEmpty(path!) !== content);
    for (const [path] of stale) console.error(`[map] stale: ${relative(REPO_ROOT, path!)}`);
    if (stale.length > 0 || issues.length > 0) failed = true;
    continue;
  }

  write(outputs.bake, bake);
  write(outputs.record, record);
  write(outputs.svg, svg);
  write(outputs.preview, preview);

  // Stats for docs/map/layout.md and docs/map/real-world.md.
  const counts = layout.props.map((set) => [set.prop, set.data.length / INSTANCE_STRIDE] as const);
  const cells = new Map<string, number>();
  for (const set of layout.props) {
    for (let i = 0; i < set.data.length; i += INSTANCE_STRIDE) {
      const key = `${Math.floor(set.data[i]! / 250)},${Math.floor(set.data[i + 2]! / 250)}`;
      cells.set(key, (cells.get(key) ?? 0) + 1);
    }
  }
  console.info(`[map] ${layout.buildings.length} buildings, ${counts.reduce((n, [, c]) => n + c, 0)} prop instances, bake ${(bake.length / 1e6).toFixed(2)} MB`);
  console.info(`[map] per prop: ${counts.map(([prop, count]) => `${prop} ${count}`).join(", ")}`);
  console.info(`[map] per scatter rule: ${Object.entries(layout.ruleCounts).map(([rule, count]) => `${rule} ${count}`).join(", ")}`);
  console.info(`[map] per 250 m cell: ${[...cells].sort().map(([key, count]) => `(${key}) ${count}`).join(", ")}`);
  if (issues.length > 0) failed = true;
}
if (check) process.exit(failed ? 1 : 0);
if (failed) process.exitCode = 1;

/**
 * Picker preview for the maze. `renderMapPreviewSvg` draws woods, water, roads and roofs; the maze is walls, so the
 * card would be an empty green square. This draws the wall lattice instead — concrete dark, glass blue — over the same
 * ground colour, then the tower roof and the POI dots the way the shared renderer does.
 */
function mazePreviewSvg(map: MapData, layout: MapLayout): string {
  const half = map.terrain.playableHalfExtent;
  const n = (v: number) => (Math.round(v * 10) / 10).toString();
  const out: string[] = [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${-half} ${-half} ${half * 2} ${half * 2}" width="512" height="512">`,
    `<rect x="${-half}" y="${-half}" width="${half * 2}" height="${half * 2}" fill="#8d9a66"/>`,
  ];

  // Each wall instance is a box lying along its own local X: a segment of `size[0]` centered on the instance.
  for (const [prop, color] of [["wall_concrete", "#514f4a"], ["wall_glass", "#7fb7c9"], ["wall_mirror", "#b9c6cc"], ["wall_grass", "#6f8f4a"]] as const) {
    const set = layout.props.find((s) => s.prop === prop);
    if (!set) continue;
    const collision = getMapProp(prop).collision;
    const reach = (collision.kind === "box" ? collision.size[0] : 4) / 2;
    const segments: string[] = [];
    for (let i = 0; i < set.data.length; i += INSTANCE_STRIDE) {
      const [x, , z, yaw, scale] = [set.data[i]!, 0, set.data[i + 2]!, set.data[i + 3]!, set.data[i + 4]!];
      const dx = Math.cos(yaw) * reach * scale;
      const dz = -Math.sin(yaw) * reach * scale;
      segments.push(`M${n(x - dx)} ${n(-(z - dz))}L${n(x + dx)} ${n(-(z + dz))}`);
    }
    if (segments.length > 0) out.push(`<path fill="none" stroke="${color}" stroke-width="1.4" stroke-linecap="square" d="${segments.join("")}"/>`);
  }

  const roofs = map.buildings.filter((b) => isBuildingPrefabId(b.prefab)).map((b) => rectCorners(prefabRectOf(getBuildingPrefab(b.prefab).bounds, [b.position[0], b.position[2]], b.yaw)));
  if (roofs.length > 0) out.push(`<path fill="#d9d2c3" stroke="#6f675b" stroke-width="1.5" d="${roofs.map((c) => `M${c.map(([x, z]) => `${n(x)} ${n(-z)}`).join("L")}Z`).join("")}"/>`);
  for (const poi of map.pois) {
    if (poi.kind === "training") continue;
    out.push(`<circle cx="${n(poi.center[0])}" cy="${n(-poi.center[1])}" r="${poi.lootTier === 2 ? 11 : 8}" fill="#f4efe3" stroke="#1d2a44" stroke-width="4"/>`);
  }
  out.push("</svg>");
  return `${out.join("\n")}\n`;
}

function write(path: string, content: string | Uint8Array): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.info(`[map] wrote ${relative(REPO_ROOT, path)} (${(content.length / 1024).toFixed(0)} KB)`);
}

function readOrEmpty(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}
