/**
 * Map v1 build step: validates the layout, bakes the terrain binary the client loads, records the bake and layout
 * checksums for the tests, and regenerates the overview SVG.
 *
 *   node --experimental-transform-types tools/map/build.ts [--check]
 *
 * Outputs:
 *   apps/client/public/assets/map/mapV1.terrain.bin     terrain heights + surface mask + paint (see terrain/bake.ts)
 *   packages/shared/src/map/layout/mapV1Bake.ts         inputs hash and checksums (asserted by mapV1.test.ts)
 *   docs/map/mapV1.svg                                  overview map
 * `--check` builds and validates without writing anything; exits 1 when outputs are stale or the layout has issues.
 */
import "./lib/resolve.ts";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { REPO_ROOT } from "./lib/resolve.ts";

setTimeout(() => {
  console.error("[map] watchdog: took longer than 5 minutes");
  process.exit(2);
}, 300_000).unref();

const shared = await import("@twobullets/shared");
const { MAP_V1, buildTerrain, buildMapLayout, validateMapLayout, encodeTerrainBake, terrainInputsHash, renderMapOverviewSvg, INSTANCE_STRIDE } = shared;
const check = process.argv.includes("--check");

const outputs = {
  bake: join(REPO_ROOT, "apps/client/public/assets/map/mapV1.terrain.bin"),
  record: join(REPO_ROOT, "packages/shared/src/map/layout/mapV1Bake.ts"),
  svg: join(REPO_ROOT, "docs/map/mapV1.svg"),
};

let started = performance.now();
const terrain = buildTerrain(MAP_V1.terrain, MAP_V1.flatten);
const terrainMs = performance.now() - started;
started = performance.now();
const layout = buildMapLayout(MAP_V1, terrain);
const layoutMs = performance.now() - started;
console.info(`[map] terrain ${terrainMs.toFixed(0)} ms (checksum ${terrain.checksum()}), layout ${layoutMs.toFixed(0)} ms (checksum ${layout.checksum})`);

const issues = validateMapLayout(MAP_V1, terrain, layout);
for (const issue of issues) console.warn(`[map] ${issue.kind}: ${issue.message}`);

const bake = await encodeTerrainBake(terrain, MAP_V1.flatten);
const record = `// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${terrainInputsHash(MAP_V1.terrain, MAP_V1.flatten)}",
  terrainChecksum: "${terrain.checksum()}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layout.checksum}",
  bytes: ${bake.length},
} as const;
`;
const svg = renderMapOverviewSvg(MAP_V1, terrain, layout);

if (check) {
  const stale = [
    [outputs.record, record],
    [outputs.svg, svg],
  ].filter(([path, content]) => readOrEmpty(path!) !== content);
  for (const [path] of stale) console.error(`[map] stale: ${relative(REPO_ROOT, path!)}`);
  process.exit(stale.length > 0 || issues.length > 0 ? 1 : 0);
}

write(outputs.bake, bake);
write(outputs.record, record);
write(outputs.svg, svg);

// Stats for docs/map/layout.md.
const counts = layout.props.map((set) => [set.prop, set.data.length / INSTANCE_STRIDE] as const);
const cells = new Map<string, number>();
for (const set of layout.props) {
  for (let i = 0; i < set.data.length; i += INSTANCE_STRIDE) {
    const key = `${Math.floor(set.data[i]! / 250)},${Math.floor(set.data[i + 2]! / 250)}`;
    cells.set(key, (cells.get(key) ?? 0) + 1);
  }
}
console.info(`[map] ${layout.buildings.length} buildings, ${counts.reduce((n, [, c]) => n + c, 0)} prop instances, bake ${(bake.length / 1e6).toFixed(2)} MB`);
console.info(`[map] per prop: ${counts.map(([prop, count]) => `${prop} ${count}`).join(", ")}`);
console.info(`[map] per scatter rule: ${Object.entries(layout.ruleCounts).map(([id, count]) => `${id} ${count}`).join(", ")}`);
console.info(`[map] per 250 m cell: ${[...cells].sort().map(([key, count]) => `(${key}) ${count}`).join(", ")}`);
if (issues.length > 0) process.exitCode = 1;

function write(path: string, content: string | Uint8Array): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.info(`[map] wrote ${relative(REPO_ROOT, path)} (${(content.length / 1024).toFixed(0)} KB)`);
}

function readOrEmpty(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}
