/**
 * Map build step: validates the layout, bakes the terrain binary the client loads, records the bake and layout
 * checksums for the tests, and regenerates the overview SVG and the small preview SVG menus show.
 *
 *   node --experimental-transform-types tools/map/build.ts [--map v1|<realMapId>|all] [--check]
 *
 * Outputs for Map v1 (the default):
 *   apps/client/public/assets/map/mapV1.terrain.bin     terrain heights + surface mask + paint (see terrain/bake.ts)
 *   packages/shared/src/map/layout/mapV1Bake.ts         inputs hash and checksums (asserted by mapV1.test.ts)
 *   docs/map/mapV1.svg                                  overview map
 *   apps/client/public/assets/map/mapV1.preview.svg     picker preview
 * Outputs for a real-world map `<id>` (generated by tools/map/osm/generate.ts):
 *   apps/client/public/assets/map/<id>.terrain.bin, packages/shared/src/map/real/<id>.bake.ts, docs/map/<id>.svg,
 *   apps/client/public/assets/map/<id>.preview.svg
 * `--check` builds and validates without writing anything; exits 1 when outputs are stale or the layout has issues.
 */
import "./lib/resolve.ts";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { REPO_ROOT } from "./lib/resolve.ts";

setTimeout(() => {
  console.error("[map] watchdog: took longer than 5 minutes");
  process.exit(2);
}, 300_000).unref();

const shared = await import("@twobullets/shared");
const { MAP_V1, buildTerrain, buildMapLayout, validateMapLayout, encodeTerrainBake, terrainInputsHash, renderMapOverviewSvg, INSTANCE_STRIDE } = shared;
const { REAL_MAPS, loadRealMap } = await import("../../packages/shared/src/map/real/index.ts");
const { renderMapPreviewSvg } = await import("../../packages/shared/src/map/real/preview.ts");
type MapData = import("@twobullets/shared").MapData;
type ValidationOptions = import("@twobullets/shared").ValidationOptions;

const check = process.argv.includes("--check");
const mapIndex = process.argv.indexOf("--map");
const mapArg = mapIndex >= 0 ? (process.argv[mapIndex + 1] ?? "v1") : "v1";
const ids = mapArg === "all" ? ["v1", ...REAL_MAPS.map((m) => m.info.id)] : [mapArg];

interface Target {
  readonly map: MapData;
  readonly validation?: ValidationOptions;
  readonly water?: readonly (readonly [number, number])[][];
  readonly outputs: { readonly bake: string; readonly record: string; readonly svg: string; readonly preview: string };
  readonly record: (inputsHash: string, terrainChecksum: string, layoutChecksum: string, bytes: number) => string;
}

async function target(id: string): Promise<Target> {
  if (id === "v1") {
    return {
      map: MAP_V1,
      outputs: {
        bake: join(REPO_ROOT, "apps/client/public/assets/map/mapV1.terrain.bin"),
        record: join(REPO_ROOT, "packages/shared/src/map/layout/mapV1Bake.ts"),
        svg: join(REPO_ROOT, "docs/map/mapV1.svg"),
        preview: join(REPO_ROOT, "apps/client/public/assets/map/mapV1.preview.svg"),
      },
      record: (inputsHash, terrainChecksum, layoutChecksum, bytes) => `// Generated by tools/map/build.ts; do not edit. Rebuild after changing MAP_V1 terrain, flatten regions or layout.
export const MAP_V1_BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${inputsHash}",
  terrainChecksum: "${terrainChecksum}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layoutChecksum}",
  bytes: ${bytes},
} as const;
`,
    };
  }
  const module = await loadRealMap(id);
  return {
    map: module.map,
    validation: module.validation,
    water: module.water as (readonly [number, number])[][],
    outputs: {
      bake: join(REPO_ROOT, `apps/client/public/assets/map/${id}.terrain.bin`),
      record: join(REPO_ROOT, `packages/shared/src/map/real/${id}.bake.ts`),
      svg: join(REPO_ROOT, `docs/map/${id}.svg`),
      preview: join(REPO_ROOT, `apps/client/public/assets/map/${id}.preview.svg`),
    },
    record: (inputsHash, terrainChecksum, layoutChecksum, bytes) => `// Generated by tools/map/build.ts --map ${id}; do not edit. Rebuild after regenerating the map.
export const BAKE = {
  /** Terrain spec + flatten regions the bake was built from. */
  inputsHash: "${inputsHash}",
  terrainChecksum: "${terrainChecksum}",
  /** Buildings, props and scatter (buildMapLayout). */
  layoutChecksum: "${layoutChecksum}",
  bytes: ${bytes},
} as const;
`,
  };
}

let failed = false;
for (const id of ids) {
  const { map, validation, water, outputs, record: recordFor } = await target(id);
  let started = performance.now();
  const terrain = buildTerrain(map.terrain, map.flatten);
  const terrainMs = performance.now() - started;
  started = performance.now();
  const layout = buildMapLayout(map, terrain);
  const layoutMs = performance.now() - started;
  console.info(`[map] ${id}: terrain ${terrainMs.toFixed(0)} ms (checksum ${terrain.checksum()}), layout ${layoutMs.toFixed(0)} ms (checksum ${layout.checksum})`);

  const issues = validateMapLayout(map, terrain, layout, validation);
  for (const issue of issues) console.warn(`[map] ${issue.kind}: ${issue.message}`);

  const bake = await encodeTerrainBake(terrain, map.flatten);
  const record = recordFor(terrainInputsHash(map.terrain, map.flatten), terrain.checksum(), layout.checksum, bake.length);
  const svg = renderMapOverviewSvg(map, terrain, layout);
  const preview = renderMapPreviewSvg(map, water ? { water } : {});

  if (check) {
    const stale = [
      [outputs.record, record],
      [outputs.svg, svg],
      [outputs.preview, preview],
    ].filter(([path, content]) => readOrEmpty(path!) !== content);
    for (const [path] of stale) console.error(`[map] stale: ${relative(REPO_ROOT, path!)}`);
    if (stale.length > 0 || issues.length > 0) failed = true;
    continue;
  }

  write(outputs.bake, bake);
  write(outputs.record, record);
  write(outputs.svg, svg);
  write(outputs.preview, preview);

  // Stats for docs/map/layout.md and docs/map/real-world.md.
  const counts = layout.props.map((set) => [set.prop, set.data.length / INSTANCE_STRIDE] as const);
  const cells = new Map<string, number>();
  for (const set of layout.props) {
    for (let i = 0; i < set.data.length; i += INSTANCE_STRIDE) {
      const key = `${Math.floor(set.data[i]! / 250)},${Math.floor(set.data[i + 2]! / 250)}`;
      cells.set(key, (cells.get(key) ?? 0) + 1);
    }
  }
  console.info(`[map] ${layout.buildings.length} buildings, ${counts.reduce((n, [, c]) => n + c, 0)} prop instances, bake ${(bake.length / 1e6).toFixed(2)} MB`);
  console.info(`[map] per prop: ${counts.map(([prop, count]) => `${prop} ${count}`).join(", ")}`);
  console.info(`[map] per scatter rule: ${Object.entries(layout.ruleCounts).map(([rule, count]) => `${rule} ${count}`).join(", ")}`);
  console.info(`[map] per 250 m cell: ${[...cells].sort().map(([key, count]) => `(${key}) ${count}`).join(", ")}`);
  if (issues.length > 0) failed = true;
}
if (check) process.exit(failed ? 1 : 0);
if (failed) process.exitCode = 1;

function write(path: string, content: string | Uint8Array): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
  console.info(`[map] wrote ${relative(REPO_ROOT, path)} (${(content.length / 1024).toFixed(0)} KB)`);
}

function readOrEmpty(path: string): string {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}
