// Generated by tools/vfx/build.mjs. Do not edit by hand.

/** "premultiplied": RGB is premultiplied by alpha; draw with ONE, ONE_MINUS_SRC_ALPHA (additive when output alpha is 0). */
export type VfxBlend = "premultiplied";

export interface VfxSheet {
  /** Relative to VFX_ASSET_ROOT. */
  readonly url: string;
  readonly hash: string;
  readonly bytes: number;
  readonly width: number;
  readonly height: number;
  readonly columns: number;
  readonly rows: number;
  /** Frames (or atlas cells), left to right then top to bottom; V = 0 is the top row. */
  readonly frames: number;
  /** Cell size in UV (cells are whole pixels from the top-left; the rest of the POT canvas is empty). */
  readonly cellU: number;
  readonly cellV: number;
  /** Authored playback rate of the flipbook (0 for atlases). */
  readonly fps: number;
  readonly loop: boolean;
  readonly blend: VfxBlend;
  /** Alpha-weighted mean luma of the straight colors (0..1): divide a target display color by it to get a tint. */
  readonly meanLuma: number;
  readonly cells?: Readonly<Record<string, number>>;
}

export const VFX_ASSET_ROOT = `${import.meta.env?.BASE_URL ?? "/"}assets/vfx/`;

export const VFX_SHEETS = {
  /** Fireball turning into dark smoke (Unity Labs Explosion01), 25 frames. Straight TGA resampled to 204 px cells. */
  explosion: {
    url: "explosion.ktx2",
    hash: "3fd7f6afec",
    bytes: 410499,
    width: 1024,
    height: 1024,
    columns: 5,
    rows: 5,
    frames: 25,
    cellU: 0.199219,
    cellV: 0.199219,
    fps: 18,
    loop: false,
    blend: "premultiplied",
    meanLuma: 0.2170,
  },
  /** Same explosion without fire (Unity Labs Explosion01-nofire): dust ring and lingering blast dust, greyscale. */
  explosionDust: {
    url: "explosion-dust.ktx2",
    hash: "e9d510b3bc",
    bytes: 117221,
    width: 512,
    height: 512,
    columns: 5,
    rows: 5,
    frames: 25,
    cellU: 0.199219,
    cellV: 0.199219,
    fps: 10,
    loop: false,
    blend: "premultiplied",
    meanLuma: 0.1535,
  },
  /** Dense rolling puff loop (Unity Labs Cloud01), 64 frames, greyscale. Smoke grenade body. */
  smokeCloud: {
    url: "smoke-cloud.ktx2",
    hash: "d115c12a31",
    bytes: 577439,
    width: 1024,
    height: 1024,
    columns: 8,
    rows: 8,
    frames: 64,
    cellU: 0.125000,
    cellV: 0.125000,
    fps: 6,
    loop: true,
    blend: "premultiplied",
    meanLuma: 0.4083,
  },
  /** Thin wispy smoke loop (Unity Labs WispySmoke01), 64 frames, greyscale. Cloud rims, fire plume, flash puff. */
  smokeWispy: {
    url: "smoke-wispy.ktx2",
    hash: "2788059eed",
    bytes: 170997,
    width: 512,
    height: 512,
    columns: 8,
    rows: 8,
    frames: 64,
    cellU: 0.125000,
    cellV: 0.125000,
    fps: 8,
    loop: true,
    blend: "premultiplied",
    meanLuma: 0.3702,
  },
  /** Licking flame loop (Unity Labs Flame03), 64 frames, base at the bottom of each 64×128 cell. */
  flame: {
    url: "flame.ktx2",
    hash: "3b78852a14",
    bytes: 239480,
    width: 1024,
    height: 512,
    columns: 16,
    rows: 4,
    frames: 64,
    cellU: 0.062500,
    cellV: 0.250000,
    fps: 30,
    loop: true,
    blend: "premultiplied",
    meanLuma: 0.6104,
  },
  /** Kenney Particle Pack sprites on a 4×4 atlas of 128 px cells: spark streak, debris, glow, flare, glass. */
  particles: {
    url: "particles.ktx2",
    hash: "da1f331d4e",
    bytes: 100030,
    width: 512,
    height: 512,
    columns: 4,
    rows: 4,
    frames: 16,
    cellU: 0.250000,
    cellV: 0.250000,
    fps: 0,
    loop: false,
    blend: "premultiplied",
    meanLuma: 0.7254,
    cells: { trace: 0, dirtCluster: 1, chunk0: 2, chunk1: 3, chunk2: 4, chunk3: 5, glow: 6, flare: 7, star: 8, halo: 9, shard0: 10, shard1: 11, shard2: 12, shard3: 13 },
  },
  /** Ground decals: burned_ground_01 albedo (Poly Haven) masked by Kenney scorch_01 (frag blast mark) and scorch_03 (molotov burn), sRGB albedo values. */
  scorch: {
    url: "scorch.ktx2",
    hash: "28fa0ad3e7",
    bytes: 404784,
    width: 1024,
    height: 512,
    columns: 2,
    rows: 1,
    frames: 2,
    cellU: 0.500000,
    cellV: 1.000000,
    fps: 0,
    loop: false,
    blend: "premultiplied",
    meanLuma: 0.1586,
    cells: { blast: 0, burn: 1 },
  },
} as const satisfies Record<string, VfxSheet>;

export type VfxSheetId = keyof typeof VFX_SHEETS;
